### PR TITLE
Added a SRV record in example_zones.toml

### PR DESCRIPTION
**Pull request by azmeuk**
It is not straightforward to guess that the answer should be an array with actual integers inside. I think this example may help users to debug their code!

### CODE REVIEW

**Comment by samuelcolvin** [comment]
We could probably add full validation and coercion to `answer` using pydantic.

**Comment by azmeuk** [comment]
This sounds like a big task :) I am not sure to have time to spend on this soon.

**Comment by samuelcolvin** [comment]
i agree, just an idea, probably better to wait for pydantic v2 where discriminated unions are more powerful.

**Comment by samuelcolvin** [comment]
PR welcome to move the toml parsing logic out of `DnsServer`, then instead of writing a toml file, you could just create `Records`.

I think there's nothing to stop you editing records/zones while the server is running.

**Pull request merged**
